// This file has been autogenerated from a class added in the UI designer.

using System;

using UIKit;

namespace StaticBind.Sample.Views.iOS
{
	public partial class MenuViewController : UIViewController
	{
		public MenuViewController (IntPtr handle) : base (handle)
		{
		}

		partial void onQuickstart(Foundation.NSObject sender)
		{
			this.PerformSegue("Quickstart", this);
		}

		partial void onSimple(Foundation.NSObject sender)
		{
			this.PerformSegue("Simple", this);
		}
	}
}
